GET http://localhost:3001

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/people

###
GET http://localhost:3001/api/people/63ef5c55b6aad3901dc79689

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
  "name": "Rest API test 2",
  "number": "11112"
}

### 
PUT http://localhost:3001/api/people/63ef5e2e79883c41ac8dcff7
Content-Type: application/json

{
  "name": "Sa",
  "number": "888-258569"
}

###
DELETE http://localhost:3001/api/people/1



// RENDER TESTS

###
GET https://part3-2.onrender.com

###
GET https://part3-2.onrender.com/info

###
GET https://part3-2.onrender.com/api/people

###
GET https://part3-2.onrender.com/api/people/63f7435f765e6050e9c6f003

###
POST https://part3-2.onrender.com/api/people
Content-Type: application/json

{
  "name": "Rest API test for Render 3",
  "number": "672"
}

### 
PUT https://part3-2.onrender.com/api/people
Content-Type: application/json

{
  "name": "Sara",
  "number": "888-258"
}

###
DELETE https://part3-2.onrender.com/api/people/63ef62da70c5c23e42342a62
